### ISSUE TITLE
[nsfw] !hentai pussy and !real pussy appear to be broken

### ISSUE THREAD

**Issue by Ultimaximus** [Onii-Chan-Discord/onii-cogs#51] opened 2021-09-23 08:54 UTC
!hentai pussy returns "Syntax: !hentai pussy \<ctx>" and putting anything after !hentai pussy causes "Error in command 'hentai pussy'. Check your console or logs for details."
Here's console:
```
[01:49:22] ERROR    [red] Exception in command 'hentai pussy'
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\Valerie\AppData\Local\redenv\lib\site-packages\discord\ext\commands\core.py:85 in wrapped                  │
│ >   85             ret = await coro(*args, **kwargs)                                                                │
│ C:\Users\Valerie\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\redbot\cogs\CogManager\cogs\nsfw\nsfw.py:348 in   │
│ pussy                                                                                                               │
│ >  348         if ctx.channel.is_nsfw():                                                                            │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'str' object has no attribute 'channel'
```
!real pussy returns "Error in command 'real pussy'. Check your console or logs for details."
Here's console:
```
[01:48:00] ERROR    [red] Exception in command 'real pussy'
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\Valerie\AppData\Local\redenv\lib\site-packages\discord\ext\commands\core.py:85 in wrapped                  │
│ >   85             ret = await coro(*args, **kwargs)                                                                │
│ C:\Users\Valerie\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\redbot\cogs\CogManager\cogs\nsfw\nsfw.py:966 in   │
│ pussy                                                                                                               │
│ >  966                 title = data["title"]                                                                        │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
KeyError: 'title'
```

I am posting this here because I cannot add Onii-chan#3920 on Discord, as it says they are not accepting friend requests

**Comment by Onii-Chan-Discord** [comment] 2021-09-30 13:23
Ah I'm sorry I just saw this issue!

For `[p]real pussy` its a reddit issue, for now that command has been disabled, I'll be looking into some fixes for this.

**Comment by Onii-Chan-Discord** [comment] 2021-09-30 13:56
Also I've been unable to reproduce your `[p]hentai pussy` error.

**Comment by Ultimaximus** [comment] 2021-09-30 14:41
[p]hentai pussy also appears to be working for me now

**Comment by Onii-Chan-Discord** [comment] 2021-10-01 03:17
That's great!

Thank you for reporting this issue!

I'll be closing this issue now.

**Closed by Onii-Chan-Discord** 2021-10-01 03:17 UTC
Labels: bug, good first issue, Category: Nsfw
